name: 'Setup Cloudflare Warp'
description: 'Sets up the Cloudflare Warp client in your GitHub Actions workflow.'
inputs:
  version:
    description: 'The version of Cloudflare Warp to install'
  organization:
    description: 'The name of your Zero Trust organization'
    required: true
  auth_client_id:
    description: 'The service token client id'
    required: true
  auth_client_secret:
    description: 'The service token client secret'
    required: true
  configure_docker_dns:
    description: 'Configure Docker to use Cloudflare WARP for DNS resolution'
    default: 'false'
  unique_client_id:
    description: 'A unique identifier for the client device'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: 'cloud'
  color: 'orange'