name: "Pull Requests"
on:
  pull_request_target:

jobs:
  approve-pr-tests:
    runs-on: ubuntu-latest
    environment:
      name: "Pull Request Tests"
    steps:
      - run: "echo 'Execution of tests pending approval'"

  lint:
    needs: ["approve-pr-tests"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: npm ci
      - run: npm run lint

  test:
    needs: ["approve-pr-tests", "lint"]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: npm ci && npm run build
      - uses: ./
        with:
          organization: ${{ secrets.CLOUDFLARE_ACCESS_ORGANIZATION }}
          auth_client_id: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}
          configure_docker_dns: true
      - run: curl -I https://www.google.com
